### ISSUE TITLE
cloud-init depends on dhcpcd-base by default: Clarify dhcpcd

### ISSUE THREAD

**Issue by jkirk** [grml/grml-live#187]
cloud-init now depends on dhcpcd-base. We still install dhcpcd as a workaround, see e530f07. 

Do we need dhcpcd or is dhcpcd-base enough?

Rational: In [#153](https://github.com/grml/grml-live/pull/153/#issuecomment-2334293946) I already mentioned that cloud-init moved to dhcpcd as the default dhcp client with v24.1, see: https://github.com/canonical/cloud-init/releases/tag/24.1.

I filed a Debian Bug [#1080999](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080999) which was fixed and the Debian package installed dhcpcd by default.

A bit later a new bug was filed: [#1082897](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082897): cloud-init should depend on dhcpcd-base rather than dhcpcd because of [#1082898](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082898): dhcpcd - Runs as service, quoting:

> dhcpcd runs itself as service, not controlled by the network management.
This makes it not a suitable replacement for isc-dhcp.

I believe we have two possibilities: 
Either we drop `DEBIAN_TESTING`, `DEBIAN_TRIXIE`, and `DEBIAN_UNSTABLE` (in https://github.com/grml/grml-live/tree/master/etc/grml/fai/config/package_config) and stick with `dhcpcd-base` provided by cloud-init or keep `dhcpcd` but put it to `GRML_FULL`.

**Comment by mika** [comment]
> cloud-init now depends on dhcpcd-base. We still install dhcpcd as a workaround, see [e530f07](https://github.com/grml/grml-live/commit/e530f07e948ce58bec9e019524a147281c25e2e1).
> 
> Do we need dhcpcd or is dhcpcd-base enough?

Thanks for raising this!

> Rational: In [#153](https://github.com/grml/grml-live/pull/153/#issuecomment-2334293946) I already mentioned that cloud-init moved to dhcpcd as the default dhcp client with v24.1, see: https://github.com/canonical/cloud-init/releases/tag/24.1.
> 
> I filed a Debian Bug [#1080999](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080999) which was fixed and the Debian package installed dhcpcd by default.
> 
> A bit later a new bug was filed: [#1082897](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082897): cloud-init should depend on dhcpcd-base rather than dhcpcd because of [#1082898](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082898): dhcpcd - Runs as service, quoting:
> 
> > dhcpcd runs itself as service, not controlled by the network management.
> > This makes it not a suitable replacement for isc-dhcp.

Ok

> I believe we have two possibilities: Either we drop `DEBIAN_TESTING`, `DEBIAN_TRIXIE`, and `DEBIAN_UNSTABLE` (in https://github.com/grml/grml-live/tree/master/etc/grml/fai/config/package_config) and stick with `dhcpcd-base` provided by cloud-init or keep `dhcpcd` but put it to `GRML_FULL`.

I don't think we can do this, as we introduced dhcpcd usage inside `DEBIAN_TESTING`, `DEBIAN_TRIXIE` and `DEBIAN_UNSTABLE` to have cloud-init support also on Debian bookworm systems (because there cloud-init has a hard dependency on isc-dhcp-client). On the other side we currently use `cloud-init` only on grml-full (but not grml-small). So we can't add neither isc-dhcp-client nor dhcpcd/dhcpcd-base to `GRML_SMALL` or `GRML_FULL`, because then building Grml ISOs based on Debian/bookworm won't work as-is. Also we can't rely on the indirect dependency on dhcpcd-base via cloud-init because a) this is true only for Debian/trixie and newer and b) won't work for grml-small.

But we control the execution of our services via systemd presets anyways. The dhcpcd service isn't active/running when booting Grml, so there doesn't seem to be any harm with the situation as-is. Though AFAICS it would be enough to replace  the `dhcpcd` package in `DEBIAN_TESTING`, `DEBIAN_TRIXIE` and `DEBIAN_UNSTABLE`  with `dhcpcd-base` and we're good?

**Comment by zeha** [comment]
> Though AFAICS it would be enough to replace the dhcpcd package in DEBIAN_TESTING, DEBIAN_TRIXIE and DEBIAN_UNSTABLE with dhcpcd-base and we're good?

I think so too

**Comment by mika** [comment]
> > Though AFAICS it would be enough to replace the dhcpcd package in DEBIAN_TESTING, DEBIAN_TRIXIE and DEBIAN_UNSTABLE with dhcpcd-base and we're good?
> 
> I think so too

Thanks, PR at https://github.com/grml/grml-live/pull/188
