### ISSUE TITLE
Cannot build grml from inside grml

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml-live#46]
This is a reminder ticket for an issue that has been discussed on the mailing list to avoid that the issue gets forgotten.

I am trying rebuild a grml iso from within grml with
sudo grml-live -A -V -s sid -c DEBORPHAN,GRMLBASE,GRML_FULL,RELEASE,AMD64,IGNORE,SNAPSHOT -r "test20170915" -g
grml64 -o ~/grml-remaster/tmp
and having this fail with a message that /efi/boot/bootx64.efi is not found at the place where the script its looking for it, while the file is in /ilb/live/mount/medium.
mika has shown a pach on the mailing list, but that patch doesn'thelp.
Full thread reference is starting at http://ml.grml.org/pipermail/grml/2017-September/011696.html

Greetings
Marc

**Comment by R-Sommer** [comment]
Just tried it successfully with Grml 2022.11 (with a workaround of failing /etc/grml/fai/config/scripts/GRMLBASE/91-update-pciids - which I wasn't able to figure out).

**Comment by mika** [comment]
@R-Sommer ok great, thanks for the feedback! Regarding the failure in `/etc/grml/fai/config/scripts/GRMLBASE/91-update-pciids`: this usually happens if the upstream website isn't available. Executing this script can be disabled via the Grml class `NO_ONLINE` during grml-live execution.

I consider this as resolved, if anyone should have any further problems please comment or open a new issue. Thx!

**Comment by R-Sommer** [comment]
Thanks @mika, the failure was due to missing proxy configuration. After adding proxy settings, I could make a successful try.
